# Generated by Django 5.2.15 on 2026-07-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_username', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('telegram_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('VK_username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('blacklisted', 'В блэклисте')], default='active', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('guest', 'Гость (первое касание)'), ('registered', 'Зарегистрирован')], default='guest', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('total_event_count', models.IntegerField(default=0)),
                ('season_event_count', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('season_hours', models.IntegerField(default=0)),
                ('churn_score', models.FloatField(default=0)),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('web_credentials_set_at', models.DateTimeField(blank=True, null=True)),
                ('notify_new_events', models.BooleanField(default=True)),
                ('notify_applications', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Константа',
                'verbose_name_plural': 'Константы',
                'db_table': 'const',
            },
        ),
        migrations.CreateModel(
            name='DobroRuSharedLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('event', 'Мероприятие'), ('organization', 'Организация'), ('project', 'Проект')], max_length=20)),
                ('period_hint', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Общая ссылка Добро.ру',
                'verbose_name_plural': 'Общие ссылки Добро.ру',
                'db_table': 'dobro_ru_shared_links',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория мероприятия',
                'verbose_name_plural': 'Категории мероприятий',
                'db_table': 'event_categories',
            },
        ),
        migrations.CreateModel(
            name='EventRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
                'db_table': 'event_requirements',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events_count', models.IntegerField(default=0)),
                ('volunteers_count', models.IntegerField(default=0)),
                ('shifts_count', models.IntegerField(default=0)),
                ('internal_rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_season', models.DateField()),
                ('end_season', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='ThankYouLetterTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Шаблон благодарственного письма',
                'verbose_name_plural': 'Шаблоны благодарственных писем',
                'db_table': 'thank_you_letter_templates',
            },
        ),
        migrations.CreateModel(
            name='BotOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=50)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка (исчерпаны попытки)')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Исходящее сообщение бота',
                'verbose_name_plural': 'Исходящие сообщения бота',
                'db_table': 'bot_outbox',
                'indexes': [models.Index(fields=['status', 'created_at'], name='bot_outbox_status_b5e3b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('chat_link', models.URLField(blank=True, null=True)),
                ('post_in_chanel_link', models.URLField(blank=True, null=True)),
                ('dobro_ru_link_kind', models.CharField(choices=[('none', 'Нет ссылки'), ('shared', 'Общая ссылка'), ('unique', 'Уникальная ссылка')], default='none', max_length=20)),
                ('dobro_ru_link', models.URLField(blank=True, null=True)),
                ('dobro_ru_hours_logged', models.BooleanField(default=False)),
                ('event_status', models.CharField(choices=[('upcoming', 'Предстоит'), ('ongoing', 'Идёт'), ('finished', 'Завершено')], default='upcoming', max_length=20)),
                ('recruit_status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('people_helped', models.IntegerField(blank=True, null=True)),
                ('internal_comment', models.TextField(blank=True, null=True)),
                ('dobro_ru_logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dobro_ru_logged_events', to=settings.AUTH_USER_MODEL)),
                ('dobro_ru_shared_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='blog.dobrorusharedlink')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='blog.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='blog.organization')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='blog.event')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'event_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('volunteer_needed', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='blog.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_days', to='blog.location')),
            ],
            options={
                'verbose_name': 'День мероприятия',
                'verbose_name_plural': 'Дни мероприятий',
                'db_table': 'event_days',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('total_events', models.IntegerField(default=0)),
                ('season_events', models.IntegerField(default=0)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_managers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('VK_username', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'db_table': 'organizers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to='blog.organizer'),
        ),
        migrations.CreateModel(
            name='OrganizerInteractionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('meeting', 'Встреча')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_interactions', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_log', to='blog.organizer')),
            ],
            options={
                'verbose_name': 'Лог взаимодействия с организатором',
                'verbose_name_plural': 'Логи взаимодействия с организаторами',
                'db_table': 'organizer_interaction_log',
            },
        ),
        migrations.CreateModel(
            name='OrganizerOrganizationLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_links', to='blog.organization')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='blog.organizer')),
            ],
            options={
                'verbose_name': 'Связь организатора и организации',
                'verbose_name_plural': 'Связи организаторов и организаций',
                'db_table': 'organizer_organization_link',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attended', 'Присутствовал'), ('absent_excused', 'Отсутствовал (уважительно)'), ('absent_unexcused', 'Отсутствовал (без предупреждения)')], default='attended', max_length=30)),
                ('full_shift', models.BooleanField(default=False)),
                ('hours', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_requested_at', models.DateTimeField(blank=True, null=True)),
                ('dobro_ru_logged', models.BooleanField(default=False)),
                ('dobro_ru_logged_at', models.DateTimeField(blank=True, null=True)),
                ('dobro_ru_logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dobro_ru_logged_participations', to=settings.AUTH_USER_MODEL)),
                ('event_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='blog.eventday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'db_table': 'participations',
            },
        ),
        migrations.CreateModel(
            name='ChurnHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('churn_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_history', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_history', to='blog.season')),
            ],
            options={
                'verbose_name': 'История чарна',
                'verbose_name_plural': 'История чарна',
                'db_table': 'churn_history',
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('total_events', models.IntegerField(default=0)),
                ('season_events', models.IntegerField(default=0)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team_leaders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тим-лидер',
                'verbose_name_plural': 'Тим-лидеры',
                'db_table': 'team_leaders',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='blog.thankyoulettertemplate'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to='blog.event')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий к волонтёру',
                'verbose_name_plural': 'Комментарии к волонтёрам',
                'db_table': 'user_comments',
            },
        ),
        migrations.CreateModel(
            name='UserRequirementException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exceptions', to='blog.eventrequirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исключение пользователя',
                'verbose_name_plural': 'Исключения пользователей',
                'db_table': 'user_requirement_exceptions',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('functions', models.CharField(blank=True, max_length=255, null=True)),
                ('shifts', models.CharField(blank=True, max_length=255, null=True)),
                ('role_in_event', models.CharField(blank=True, max_length=255, null=True)),
                ('user_status', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена/резерв')], default='new', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='blog.event')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
                'indexes': [models.Index(fields=['event', 'status'], name='application_event_i_9e8587_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventCategoryMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_map', to='blog.eventcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_map', to='blog.event')),
            ],
            options={
                'verbose_name': 'Категория мероприятия (связь)',
                'verbose_name_plural': 'Категории мероприятий (связи)',
                'db_table': 'event_category_map',
                'unique_together': {('event', 'category')},
            },
        ),
        migrations.CreateModel(
            name='EventRequirementMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_map', to='blog.event')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_map', to='blog.eventrequirement')),
            ],
            options={
                'verbose_name': 'Требование мероприятия (связь)',
                'verbose_name_plural': 'Требования мероприятий (связи)',
                'db_table': 'event_requirement_map',
                'unique_together': {('event', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='EventStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('manager', 'Менеджер'), ('team_lead', 'Тим-лидер')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='blog.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонал мероприятия',
                'verbose_name_plural': 'Персонал мероприятий',
                'db_table': 'event_staff',
                'indexes': [models.Index(fields=['event', 'staff_role'], name='event_staff_event_i_cb4a9c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eventday',
            index=models.Index(fields=['event'], name='event_days_event_i_8e65d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizerorganizationlink',
            unique_together={('organizer', 'organization')},
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'event_day'], name='participati_user_id_778c60_idx'),
        ),
        migrations.AddIndex(
            model_name='churnhistory',
            index=models.Index(fields=['user', 'season'], name='churn_histo_user_id_8d8834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrequirementexception',
            unique_together={('user', 'requirement')},
        ),
    ]
