# Generated by Django 5.2.15 on 2026-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('upcoming', 'Предстоит'), ('ongoing', 'Идёт'), ('passed', 'Прошло'), ('finished', 'Завершено')], default='upcoming', max_length=20),
        ),
    ]
