# Generated by Django 5.2.15 on 2026-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_eventday_event_remove_eventday_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected_shifts',
            field=models.ManyToManyField(blank=True, related_name='applications', to='blog.eventshift'),
        ),
    ]
