# Generated by Django 5.2.15 on 2026-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_application_selected_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
