# Generated by Django 5.2.15 on 2026-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_location_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена/резерв'), ('cancelled', 'Отменена волонтёром')], default='new', max_length=20),
        ),
    ]
