# Generated by Django 5.2.15 on 2026-07-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_application_cancel_reason_application_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_event_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.event')),
            ],
            options={
                'verbose_name': 'Комментарий к мероприятию',
                'verbose_name_plural': 'Комментарии к мероприятиям',
                'db_table': 'event_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
