# Generated by Django 5.2.15 on 2026-07-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_eventcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingButtonRemoval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=50)),
                ('message_id', models.BigIntegerField()),
                ('remove_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отложенное снятие кнопок',
                'verbose_name_plural': 'Отложенные снятия кнопок',
                'db_table': 'pending_button_removals',
                'indexes': [models.Index(fields=['remove_at'], name='pending_but_remove__a61f4c_idx')],
            },
        ),
    ]
