# Generated by Django 5.2.15 on 2026-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_pendingbuttonremoval'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
