# Generated by Django 5.2.15 on 2026-07-07 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationShiftDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена/резерв')], default='new', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_decisions', to='blog.application')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_shift_decisions', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_decisions', to='blog.eventshift')),
            ],
            options={
                'verbose_name': 'Решение по смене заявки',
                'verbose_name_plural': 'Решения по сменам заявок',
                'db_table': 'application_shift_decisions',
                'unique_together': {('application', 'shift')},
            },
        ),
    ]
