# Generated by Django 5.2.15 on 2026-07-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_applicationshiftdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('changed', 'Изменена'), ('withdrawn', 'Отозвана'), ('new', 'Новая')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='blog.application')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_change_logs', to='blog.event')),
            ],
            options={
                'verbose_name': 'Запись об изменении заявки',
                'verbose_name_plural': 'Записи об изменениях заявок',
                'db_table': 'application_change_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
