# Generated by Django 5.2.15 on 2026-07-08 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_event_tokens(apps, schema_editor):
    Event = apps.get_model('blog', 'Event')
    for event in Event.objects.all():
        event.public_token = uuid.uuid4()
        event.save(update_fields=['public_token'])


def gen_user_tokens(apps, schema_editor):
    User = apps.get_model('blog', 'User')
    for user in User.objects.all():
        user.experience_token = uuid.uuid4()
        user.save(update_fields=['experience_token'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_event_people_helped_alter_eventfeedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='broadcast_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # public_token: добавляем без unique, заполняем уникальными UUID на каждую
        # строку, затем включаем uniqueness (callable default одиночно не гарантирует
        # уникальность на существующих строках).
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_event_tokens, noop),
        migrations.AlterField(
            model_name='event',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_user_tokens, noop),
        migrations.AlterField(
            model_name='user',
            name='experience_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ExternalExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Внешний опыт',
                'verbose_name_plural': 'Внешний опыт',
                'db_table': 'external_experiences',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен входа через Telegram',
                'verbose_name_plural': 'Токены входа через Telegram',
                'db_table': 'telegram_auth_tokens',
            },
        ),
    ]
